const mongoose = require('mongoose');

const ConfigSchema = new mongoose.Schema({
  key: { type: String, required: true, unique: true },
  fbToken: { type: String, default: '' },
  fbTokenExpiresAt: { type: Date },
  fbTokenLastRefreshTime: { type: Date },
  fbTokenLastDebugTime: { type: Date },
  fbTokenLastRefreshError: { type: String, default: '' },
  claudeKey: { type: String, default: '' },
  geminiKey: { type: String, default: '' },
  fbAppId: { type: String, default: '' },
  fbAppSecret: { type: String, default: '' },
  pancakeApiKey: { type: String, default: '' },
  pancakeShopId: { type: String, default: '' },
  autoRuleStartTime: { type: String, default: '00:00' },
  autoRuleEndTime: { type: String, default: '09:00' },
  shopeeAutoRuleStartTime: { type: String, default: '00:00' },
  shopeeAutoRuleEndTime: { type: String, default: '09:00' },
  scheduledDuplicatePauseTime: { type: String, default: '21:00' },
  
  dailyZeroMessageSpendLimit: { type: Number, default: 25000 },
  dailyOneMessageSpendLimit: { type: Number, default: 25000 },
  dailyFewMessageThreshold: { type: Number, default: 0 },
  dailyFewMessageSpendLimit: { type: Number, default: 0 },
  dailyCheapMessageCostLimit: { type: Number, default: 0 },
  dailyCheapMessageSpendLimit: { type: Number, default: 0 },
  dailyHighCostPerMessageLimit: { type: Number, default: 20000 },
  dailyHighCostSpendLimit: { type: Number, default: 50000 },
  dailyClickLimit: { type: Number, default: 0 },
  dailyCpcLimit: { type: Number, default: 500 },

  lifetimeZeroMessageSpendLimit: { type: Number, default: 25000 },
  lifetimeOneMessageSpendLimit: { type: Number, default: 25000 },
  lifetimeFewMessageThreshold: { type: Number, default: 0 },
  lifetimeFewMessageSpendLimit: { type: Number, default: 0 },
  lifetimeCheapMessageCostLimit: { type: Number, default: 0 },
  lifetimeCheapMessageSpendLimit: { type: Number, default: 0 },
  lifetimeHighCostPerMessageLimit: { type: Number, default: 20000 },
  lifetimeHighCostSpendLimit: { type: Number, default: 50000 },
  lifetimeClickLimit: { type: Number, default: 0 },
  lifetimeCpcLimit: { type: Number, default: 500 },
  autoPauseCpoLimit: { type: Number, default: 100000 },
  autoPauseCpoLimitLifetime: { type: Number, default: 100000 },
  autoPauseZeroOrderSpendLimit: { type: Number, default: 60000 },
  autoPauseZeroOrderSpendLimitLifetime: { type: Number, default: 60000 },
  autoPauseShopeeMinSpendLimit: { type: Number, default: 50000 },
  autoPauseShopeeHhAdsPercent: { type: Number, default: 15 },
  dataPurchaseOrderMeta: { type: mongoose.Schema.Types.Mixed, default: {} },
  purchaseOrderDashboardCancellations: { type: mongoose.Schema.Types.Mixed, default: {} },
  purchaseOrderDashboardNotes: { type: mongoose.Schema.Types.Mixed, default: {} },
  dealStopOrderState: { type: mongoose.Schema.Types.Mixed, default: {} },

  updatedAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Config', ConfigSchema);
